version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Installing dependencies
          command: |
            pip install -r requirements.txt
            pytest